name: Commit changes
description: Commit and push changes back to the source branch when files have been modified

inputs:
  commit-message:
    description: Commit message to use when committing changes
    required: false
    default: "chore(fmt): From CI 🤖"
  ref:
    description: Branch or ref to push changes to
    required: false
    default: ""
  user-name:
    description: Git user name for committing
    required: false
    default: "tcrypt25519"
  user-email:
    description: Git user email for committing
    required: false
    default: "mail@tcry.pt"

runs:
  using: composite
  steps:
    - name: Get target ref
      id: get_target
      run: |
          if [ -n "${{ inputs.ref }}" ]; then
            TARGET_REF="${{ inputs.ref }}"
          else
            TARGET_REF=$(git rev-parse --abbrev-ref HEAD)
          fi
          echo "Found target ref: $TARGET_REF"
          echo "ref=$TARGET_REF" >> $GITHUB_OUTPUT
        
    - name: Commit and push changes
      shell: bash
      run: |
        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit ✅"
        else
          git config user.name "${{ inputs.user-name }}"
          git config user.email "${{ inputs.user-email }}"

          REF=${{ steps.get_target.outputs.ref }}
          git fetch --all
          git pull origin $REF
          git commit -m "${{ inputs.commit-message }}"
          git push origin HEAD:$REF
        fi
